/**
 * Generates a buffer containing a series of randomly generated bytes.
 *
 * Note: This duplicates `randomBytes` in `api/src/utils/index.ts`, kept isolated
 * so the contract test suite has no runtime dependency on the API workspace.
 *
 * @param length The number of bytes to generate.
 * @returns A `Uint8Array` representing `length` randomly generated bytes.
 */
export const randomBytes = (length: number): Uint8Array => {
  const bytes = new Uint8Array(length);
  crypto.getRandomValues(bytes);
  return bytes;
};
